import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '../../');
const questionnairePath = path.resolve(__dirname, '../mappings/questionnaire-map.json');
const ancillaryPath = path.resolve(__dirname, '../mappings/ancillary-maps.json');
const outputPath = path.join(ROOT, 'frontend', 'types', 'schema.ts');

function ensureOutputDir() {
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function readJson(filePath: string) {
  const raw = fs.readFileSync(filePath, 'utf8');
  return JSON.parse(raw);
}

function generateFileContent(questionnaire: unknown, ancillary: unknown) {
  const header = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.\n// Generated by backend/scripts/generate-types.ts\n\n`;
  const schemaValueType = `export type SchemaValue = string | number | boolean | null | SchemaValue[] | { [key: string]: SchemaValue };`;

  const questionnaireConst = `export const questionnaireMap = ${JSON.stringify(questionnaire, null, 2)} as const;\nexport type QuestionnaireMap = typeof questionnaireMap;`;
  const ancillaryConst = `export const ancillaryMaps = ${JSON.stringify(ancillary, null, 2)} as const;\nexport type AncillaryMaps = typeof ancillaryMaps;`;

  return `${header}${schemaValueType}\n\n${questionnaireConst}\n\n${ancillaryConst}\n`;
}

function main() {
  ensureOutputDir();
  const questionnaire = readJson(questionnairePath);
  const ancillary = readJson(ancillaryPath);
  const content = generateFileContent(questionnaire, ancillary);
  fs.writeFileSync(outputPath, content, 'utf8');
  console.log(`✅ Generated ${path.relative(ROOT, outputPath)}`);
}

main();

